SELECT * FROM couriermanagementsystem.courier;
USE couriermanagementsystem;

ALTER TABLE COURIER MODIFY COLUMN LastName VARCHAR(20);

ALTER TABLE courier DROP COLUMN LASTNAME ;

UPDATE COURIER SET VehicleType = 'CAR' WHERE CourierID = 7;

ALTER TABLE COURIER ADD DELIVERY_ADDRESS VARCHAR(50);

DELETE FROM COURIER WHERE CourierID = 6;

SELECT * FROM COURIER JOIN PAYMENT ON COURIER.CourierID = PAYMENT.CustomerID;

SELECT * FROM COURIER ORDER BY LastName;

SELECT * FROM COURIER  
LEFT JOIN PAYMENT ON COURIER.CourierID = PAYMENT.CustomerID
LEFT JOIN DISCOUNT ON PAYMENT.OrderID = DISCOUNT.OrderID;

SELECT DISTINCT VehicleType
FROM COURIER;

SELECT *
FROM COURIER
INNER JOIN PAYMENT ON COURIER.CourierID = PAYMENT.CustomerID;

SELECT * FROM COURIER LEFT OUTER JOIN PAYMENT ON COURIER.CourierID = PAYMENT.CustomerID;

