SELECT * FROM couriermanagementsystem.customer_complaints;

ALTER TABLE CUSTOMER_COMPLAINTS MODIFY COLUMN Description  VARCHAR(200);

SELECT * FROM CUSTOMER INNER JOIN CUSTOMER_COMPLAINTS ON CUSTOMER.CustomerID = CUSTOMER_COMPLAINTS.CustomerID;

SELECT * FROM CUSTOMER LEFT JOIN CUSTOMER_COMPLAINTS ON CUSTOMER.CustomerID = CUSTOMER_COMPLAINTS.CustomerID;

SELECT * FROM CUSTOMER INNER JOIN CUSTOMER_COMPLAINTS ON CUSTOMER.CustomerID = CUSTOMER_COMPLAINTS.CustomerID;



SELECT CustomerID FROM CUSTOMER_COMPLAINTS WHERE Status = 'IN PROGRESS';
SELECT * FROM CUSTOMER LEFT JOIN CUSTOMER_COMPLAINTS ON CUSTOMER.FIRSTNAME = CUSTOMER_COMPLAINTS.CustomerID WHERE STATUS = 'IN PROGRESS';

SELECT CUSTOMER.FIRSTNAME FROM CUSTOMER JOIN CUSTOMER_COMPLAINTS ON 
CUSTOMER.CUSTOMERID = customer_COMPLAINTS.CustomerID WHERE Status = 'IN PROGRESS';

SELECT CUSTOMER.CUSTOMERID, CUSTOMER.FIRSTNAME FROM CUSTOMER JOIN CUSTOMER_COMPLAINTS ON CUSTOMERID = CUSTOMER_COMPLAINTS.CustomerID WHERE STATUS = 'IN PROGRESS';

